FROM python:3.7-buster

RUN : \
    && export PIP_EXTRA_INDEX_URL="https://www.piwheels.org/simple" \
    && pip install \
        pytest-embedded \
        pytest-embedded-idf \
        pytest-embedded-serial-esp \
    && :
