name: Build and push Docker image 'kedarsovani_esp_matter'

on:
  push:
    branches:
      - master
    paths:
      - 'kedarsovani_esp_matter/**'
      - '.github/workflows/build_image_kedarsovani_esp_matter.yml'

  pull_request:
    paths:
      - 'kedarsovani_esp_matter/**'
      - '.github/workflows/build_image_kedarsovani_esp_matter.yml'

env:
  IMAGE_DIR: ./kedarsovani_esp_matter
  IMAGE_NAME: ghcr.io/${{ github.repository }}/kedarsovani_esp_matter
  IMAGE_TAG: v1
  IMAGE_ARCHS: linux/arm,linux/arm64

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHRC
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ${{env.IMAGE_DIR}}
          platforms: ${{env.IMAGE_ARCHS}}
          tags: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          # Push package to registry only when merged to master
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
